import React, { useState } from 'react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { serviceAccountService } from '../services/services'
import { FaEye, FaEdit, FaTrash, FaToggleOn, FaToggleOff } from 'react-icons/fa'
import '../styles/OpenAIKeys.css'
import { showError, showSuccess } from '../utils/toast'

function OpenAIKeys() {
  const queryClient = useQueryClient()
  const [showAddForm, setShowAddForm] = useState(false)
  const [formData, setFormData] = useState({ key_name: '' }) // No api_key input - generated by backend
  const [visibleKeys, setVisibleKeys] = useState({})
  const [maskedKeys, setMaskedKeys] = useState({})
  const [errorMessage, setErrorMessage] = useState(null)

  // Fetch list of service accounts
  const { data: keys, isLoading } = useQuery({
    queryKey: ['service-accounts'],
    queryFn: serviceAccountService.list, // Update service
  })

  // Create mutation (backend generates key)
  const createMutation = useMutation({
    mutationFn: serviceAccountService.create,
    onSuccess: () => {
      queryClient.invalidateQueries(['service-accounts'])
      setShowAddForm(false)
      setFormData({ key_name: '' })
      setErrorMessage(null)
    },
    onError: (error) => {
      setErrorMessage(error.response?.data?.detail || 'Failed to create service account')
    },
  })

  // Delete mutation
  const deleteMutation = useMutation({
    mutationFn: serviceAccountService.delete,
    onSuccess: () => {
      queryClient.invalidateQueries(['service-accounts'])
      setErrorMessage(null)
    },
    onError: (error) => {
      const detail = error.response?.data?.detail
      if (typeof detail === 'object' && detail.message) {
        const agentList = detail.agents?.join(', ') || ''
        setErrorMessage(`${detail.message} Agents: ${agentList}. ${detail.hint || ''}`)
      } else {
        setErrorMessage(detail || 'Failed to delete service account')
      }
    },
  })

  // Toggle active status
  const toggleMutation = useMutation({
    mutationFn: serviceAccountService.toggle,
    onMutate: async (keyId) => {
      await queryClient.cancelQueries({ queryKey: ['service-accounts'] })
      const previousKeys = queryClient.getQueryData(['service-accounts'])
      
      queryClient.setQueryData(['service-accounts'], (old) => {
        return old?.map(key => 
          key.id === keyId 
            ? { ...key, is_active: !key.is_active }
            : key
        )
      })
      
      return { previousKeys }
    },
    onSuccess: () => {
      setErrorMessage(null)
      showSuccess("Service account key updated successfully")
    },
    onError: (error, keyId, context) => {
      queryClient.setQueryData(['service-accounts'], context.previousKeys)
      setErrorMessage(error.response?.data?.detail || 'Failed to toggle status')
      showError("Key not updated")
    },
  })

  const handleSubmit = (e) => {
    e.preventDefault()
    createMutation.mutate(formData)
  }

  const toggleKeyVisibility = async (keyId) => {
    if (visibleKeys[keyId]) {
      setVisibleKeys(prev => ({ ...prev, [keyId]: false }))
    } else {
      if (!maskedKeys[keyId]) {
        try {
          const data = await serviceAccountService.getMasked(keyId)
          setMaskedKeys(prev => ({ ...prev, [keyId]: data.masked_key }))
        } catch (error) {
          console.error('Error fetching masked key:', error)
          return
        }
      }
      setVisibleKeys(prev => ({ ...prev, [keyId]: true }))
    }
  }

  if (isLoading) return <div>Loading service accounts...</div>

  return (
    <div className="service-accounts">
      <div className="page-header">
        <h1>OpenAI Service Accounts</h1>
        <button onClick={() => setShowAddForm(!showAddForm)}>
          {showAddForm ? 'Cancel' : '+ Generate New Key'}
        </button>
      </div>

      {errorMessage && (
        <div className="error-banner">
          <span>{errorMessage}</span>
          <button onClick={() => setErrorMessage(null)} className="close-btn">×</button>
        </div>
      )}

      {showAddForm && (
        <form onSubmit={handleSubmit} className="add-key-form">
          <input
            type="text"
            value={formData.key_name}
            onChange={(e) => setFormData({ ...formData, key_name: e.target.value })}
            required
            placeholder="Key Name (e.g. Main Account)"
          />
          <button type="submit">Generate Key</button>
        </form>
      )}

      <div className="keys-list">
        {keys?.map((key) => (
          <div key={key.id} className="key-card">
            <div className="key-info">
              <h3>{key.key_name}</h3>
              <div className="key-meta">
                <span className={`status ${key.is_active ? 'active' : 'inactive'}`}>
                  {key.is_active ? 'Active' : 'Inactive'}
                </span>
                <div className="service-id">
                  <small>ID: {key.openai_service_account_id}</small>
                </div>
              </div>
              {visibleKeys[key.id] && (
                <div className="masked-key">
                  <code>{maskedKeys[key.id] || 'Loading...'}</code>
                </div>
              )}
            </div>
            <div className="key-actions">
              <button
                className="action-btn view-btn"
                onClick={() => toggleKeyVisibility(key.id)}
                title={visibleKeys[key.id] ? "Hide Key" : "View Key"}
              >
                <FaEye />
              </button>
              <button
                className="action-btn edit-btn"
                onClick={() => toggleMutation.mutate(key.id)}
                title={key.is_active ? "Deactivate" : "Activate"}
              >
                {key.is_active ? <FaToggleOn /> : <FaToggleOff />}
              </button>
              <button
                className="action-btn delete-btn"
                onClick={() => deleteMutation.mutate(key.id)}
                title="Delete Key"
              >
                <FaTrash />
              </button>
            </div>
          </div>
        ))}
        {keys?.length === 0 && <p>No service accounts generated yet.</p>}
      </div>
    </div>
  )
}

export default OpenAIKeys

