#!/usr/bin/env python3
"""
Helper script to check and update HubSpot OAuth scopes
"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from app.config import settings

print("=" * 80)
print("HubSpot OAuth Scope Configuration")
print("=" * 80)
print()
print("Current configured scopes in code:")
print(f"  {settings.hubspot_oauth_scopes}")
print()
print("=" * 80)
print("HOW TO FIX SCOPE MISMATCH ERROR:")
print("=" * 80)
print()
print("1. Go to HubSpot Developer Portal:")
print("   https://app.hubspot.com/developers")
print()
print("2. Select your app (App ID: 26701588)")
print()
print("3. Navigate to: Auth -> Scopes")
print()
print("4. Check what scopes are configured:")
print("   - Required scopes")
print("   - Optional scopes")
print()
print("5. Update the scopes in config.py to match EXACTLY:")
print("   - Option A: Edit backend/app/config.py")
print("     Change: hubspot_oauth_scopes = 'your-scopes-here'")
print()
print("   - Option B: Set environment variable")
print("     export HUBSPOT_OAUTH_SCOPES='your-scopes-here'")
print()
print("=" * 80)
print("COMMON HUBSPOT SCOPES:")
print("=" * 80)
print()
print("For CRM access (contacts & companies):")
print("  crm.objects.contacts.read")
print("  crm.objects.contacts.write")
print("  crm.objects.companies.read")
print("  crm.objects.companies.write")
print()
print("For schema access:")
print("  crm.schemas.contacts.read")
print("  crm.schemas.companies.read")
print()
print("Minimal (contacts only):")
print("  crm.objects.contacts.read crm.objects.contacts.write")
print()
print("=" * 80)
print("IMPORTANT:")
print("=" * 80)
print("The scopes in the OAuth URL MUST match EXACTLY what's configured")
print("in your HubSpot app settings. Check the app settings first!")
print("=" * 80)

